# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    files_directory: '%kernel.project_dir%/web/uploads/files'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    users_service:
        class: AppBundle\Services\UserService
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'

    mail_service:
        class: AppBundle\Services\MailService
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'

    mail_service.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    mail_service.registration_complete:
        class: AppBundle\EventListener\RegistrationConfirmListener
        arguments:
            - '@router'
        tags:
            - { name: kernel.event_subscriber }